### ISSUE TITLE
c.forEach is not a function

### ISSUE THREAD

**Issue by AngZhai** [scalabel/scalabel#1]
hello，can you help me:
 I just use default profile to test.  when I press the submit button in my browser，it shows"c.forEach is not a function". 
And when i use this command " python3 scripts/prepare_data.py -i data/basket-2_1.mp4 -t data/output/basket-1/ -f 5" to process my video，it shows success, but the output "image_list.yml" is empty.
thank you very much!!

**Comment by fyu** [comment]
The javascript error should be fixed in the master now.
