### ISSUE TITLE
2d bounding box tracking not working

### ISSUE THREAD

**Issue by shridharmishra4** [scalabel/scalabel#104]
**Describe the bug**
Bounding box interpolation fails on subsequent frames for video object tracking. System freezes with errors on all frames of the video.

**To Reproduce**
Init a 2D bounding box on the key frame and click play.

**Expected behavior**
Bounding box form the key frame should have been interpolated on the next frame on clicking play button.

**Screenshots**
<img width="840" alt="Screenshot 2020-04-24 at 11 08 15 AM" src="https://user-images.githubusercontent.com/3767131/80243456-1a7fa280-861c-11ea-968a-66b8efe9ea95.png">

**Desktop (please complete the following information):**
OS: MacOS
Browser Chrome Version 81.0.4044.113 & Safari Version 13.1 (15609.1.20.111.8)

**Additional context**
commit 3ceaa8.

**Comment by shridharmishra4** [comment]
Similar to https://github.com/scalabel/scalabel/issues/100#issue-605113687

**Comment by sinnyn** [comment]
Thanks for the report. It looks like a recent change breaks it. We'll fix it soon.

**Comment by EnnaSachdeva** [comment]
Does it work now? I'm facing the similar issue, bounding box interpolation is not working.

**Comment by fyu** [comment]
@EnnaSachdeva The problem should have been fixed in the master branch now. Are you still experiencing the issue?
