### ISSUE TITLE
Track Linking and link segmentation labels

### ISSUE THREAD

**Issue by ravich3373** [scalabel/scalabel#134]
Hi, I am trying to annotate for an instance segmentation task, where due to occulsion i need to use link segmentation label feture as shown in the docs, but the ui gets stuck at "saving in process" after linking the masks, i am able to use track linking feature with success, and both these features have the same shortcut (ctrl+L), how can i use link labels feature? 

i use item type as "video", label type as "instance segmentation", prvide itemlist, cateogery list, attribute list as needed.

I have compiled from source on ubuntu system.

**Comment by sinnyn** [comment]
Do you have any server log while you're saving?

**Comment by ravich3373** [comment]
{
  level: 'info',
  message: 'Requesting /getExport?project_name=vid_seg_new',
  timestamp: '2020-05-15T06:14:30.159Z'
}
{
  level: 'error',
  message: "Cannot read property 'id' of undefined",
  trace: "TypeError: Cannot read property 'id' of undefined\n" +
    '    at /home/ravi/hdd/scalable_2/scalabel/app/dist/js/main.js:1:11119\n' +
    '    at St (/home/ravi/hdd/scalable_2/scalabel/app/dist/js/main.js:1:11334)\n' +
    '    at Ct (/home/ravi/hdd/scalable_2/scalabel/app/dist/js/main.js:1:17548)\n' +
    '    at /home/ravi/hdd/scalable_2/scalabel/node_modules/redux-undo/lib/reducer.js:211:23\n' +
    '    at dispatch (/home/ravi/hdd/scalable_2/scalabel/node_modules/redux/lib/redux.js:219:22)\n' +
    '    at Object.dispatch (/home/ravi/hdd/scalable_2/scalabel/node_modules/redux-thunk/lib/index.js:14:16)\n' +
    '    at /home/ravi/hdd/scalable_2/scalabel/app/dist/js/main.js:1:107978\n' +
    '    at gi.<anonymous> (/home/ravi/hdd/scalable_2/scalabel/app/dist/js/main.js:1:108021)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at r (/home/ravi/hdd/scalable_2/scalabel/app/dist/js/main.js:1:106261)',
  timestamp: '2020-05-15T06:16:14.499Z'
}
5633:M 15 May 2020 11:46:17.015 * 10 changes in 300 seconds. Saving...
5633:M 15 May 2020 11:46:17.015 * Background saving started by pid 6728
6728:C 15 May 2020 11:46:17.056 * DB saved on disk
6728:C 15 May 2020 11:46:17.056 * RDB: 0 MB of memory used by copy-on-write
5633:M 15 May 2020 11:46:17.116 * Background saving terminated with success
{
  level: 'info',
  message: 'Reading new_vid_sem_seg/saved/000000/2020-05-14_17-31-32\n',
  timestamp: '2020-05-15T06:22:38.160Z'
}

**Comment by ravich3373** [comment]
reads saving is success, but the web ui shows saving in progress, if i reaload a white page is diaplyed and cant access project anymore.

**Comment by ravich3373** [comment]
closing this isses, since no responce.
I've moved to a different annotation tool, Labelme.
