### ISSUE TITLE
Image / Lane labeling, Categories of names are not displayed on the image

### ISSUE THREAD

**Issue by onuraktas61** [scalabel/scalabel#146]
Have a nice day;

1.)As I mentioned in the title.
I was using the previous version of scalabel. I had to replace my computer.
I am currently using your current version.
There are problems; In the Lane labeling, I cannot see the names of my names in the category section on the pictures.
As an example; I make a road label, I tag it in lane section as a strip, but I just can't see which category it belongs to on the line.

In 2Dbox labeling, the boxes belong to any category with their names, but not in lane labeling.
I would be very glad if you could help with this.

2.)In addition, when we download the json file after the tagging is finished, it randomly specifies the id part in the index part in the file.
In the old version, ids were sorted according to the ranking, in the new version we write random numbers, we can not follow when there is a problem with the labeling.

Ubuntu 16.04 
Chrome
![Capture_index_2](https://user-images.githubusercontent.com/60302833/83849770-93dcdb80-a718-11ea-9cef-a5777aa95a85.JPG)

![Capture_index_LI](https://user-images.githubusercontent.com/60302833/83849774-963f3580-a718-11ea-889a-a1573a12a846.jpg)

![Capture](https://user-images.githubusercontent.com/60302833/83849752-8de6fa80-a718-11ea-8736-859701cbbc3b.JPG)

**Comment by heruili** [comment]
I also have this problem, are you solved

**Comment by fyu** [comment]
This should be resolved in the latest master.
