### ISSUE TITLE
No interpolation or end object track button

### ISSUE THREAD

**Issue by johnperuzzi** [scalabel/scalabel#166]
Trying to do 2D bounding box tracking, and there is no between frame interpolation and no "end object track" button. It kind of looks like it thinks I'm just detection and not tracking. Not sure if I'm somehow setting up wrong. It's annoying to have to redraw every frame

My setup looks like 
<img width="792" alt="Screen Shot 2020-07-02 at 8 53 24 PM" src="https://user-images.githubusercontent.com/37786018/86420963-364f9680-bca6-11ea-966f-6a76cc1bf70d.png">

and then dashboard looks like
<img width="1260" alt="Screen Shot 2020-07-02 at 8 53 40 PM" src="https://user-images.githubusercontent.com/37786018/86420981-3ea7d180-bca6-11ea-9e61-e9e9db0c8235.png">

and then task link looks like

 
<img width="1280" alt="Screen Shot 2020-07-02 at 8 53 58 PM" src="https://user-images.githubusercontent.com/37786018/86421001-52533800-bca6-11ea-9730-44ed07a067a7.png">

**Comment by fyu** [comment]
What you did looks all good. When you draw a box on the first frame, the box will be propagated to the other frames. Currently, we don't have a separate "end object track" button. We have merged that functionality with the delete button. If an object is labeled from Frame 1 to 10 and you delete the box on Frame 5, the boxes for the object will only remain on Frame 1 to 4.

**Comment by EnnaSachdeva** [comment]
Bounding box propagation doesn't seem to work in the current updated repo as well. Any updates on this?

**Comment by fyu** [comment]
@EnnaSachdeva The propagation should be working now. If you meet a concrete problem, feel free to open a new issue.
