### ISSUE TITLE
2DLane Polyline Tag 

### ISSUE THREAD

**Issue by onuraktas61** [scalabel/scalabel#167]
1.)Polyline Tag may be better if seen .

2.)In addition, when we download the json file after the tagging is finished, it randomly specifies the id part in the index part in the file.
In the old version, ids were sorted according to the ranking, in the new version we write random numbers, we can not follow when there is a problem with the labeling.

![Screenshot from 2020-07-03 14-10-34](https://user-images.githubusercontent.com/60302833/86463876-056b7200-bd37-11ea-9140-47e896c1110b.png)

![Screenshot from 2020-07-03 14-13-57](https://user-images.githubusercontent.com/60302833/86464145-94788a00-bd37-11ea-92b1-2074be86b233.png)

**Comment by fyu** [comment]
1) Polyline tag is added in #169 
2) The order of the labels is their drawing order. The random string id is used to support the synchronization of multiple sessions, model-assisted annotation, and global tracing of labels in a project.

**Comment by onuraktas61** [comment]
Full Clear  setup although i try its not working polyline tag.

**Comment by fyu** [comment]
hmm... after updating to the latest master, do you still have the same problem?

**Comment by onuraktas61** [comment]
Yes, Polyline and Polygon I cant see Tag .
(Windows and Linux try).

**Comment by fyu** [comment]
It may be because your browser stilled used the old code in cache. Are you installing from docker or source build?

**Comment by fyu** [comment]
I am closing this issue because it is supposed to be fixed and lack of activity. Feel free to revisit this issue if the problem persists.
