### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by shridharmishra4** [scalabel/scalabel#189]
**Describe the bug**
Unable to create project after launching the server
commit: https://github.com/scalabel/scalabel/commit/9c7cf21be1a0bf9960eb74c062c8cf5361276d6a
**To Reproduce**
Click on create server after homepage.
http://localhost:8686/create not found.

**Expected behavior**

**Screenshots**
[
<img width="1242" alt="Screenshot 2020-07-23 at 5 04 30 PM" src="https://user-images.githubusercontent.com/3767131/88350075-d11c1d80-cd06-11ea-9671-7eae97e32fff.png">
](url)

**Desktop (please complete the following information):**
 - OS:MacOS

**Comment by fyu** [comment]
Can you provide me some additional info?
1. You can open http://localhost:8686, right?
2. What's the data directory setup in the input config file?
3. What's currently in that directory?
4. What do you get from http://localhost:8686/getProjectNames?

**Comment by shridharmishra4** [comment]
Sorry for the late reply.
I got it to work by running the JS code directly or through your old run server python code without changing anything else. Maybe its just the binary which was compiled didn't work..
