### ISSUE TITLE
Move types and contants from files to the right folders

### ISSUE THREAD

**Issue by fyu** [scalabel/scalabel#199]
Under `app/src/js`, each folder has its own `types.ts`. Those files are containing both interfaces and constant definitions. They are growing bigger. It is also harder to find the proper file to put a new type, because a lot of the type files are referenced from multiple modules (subfolders under `js`) and they are used in both frontend and backend. We shall move them to `types` and `const` folders for the separation of different definitions and easier sharing between modules. It will also be easier to look up the relevant variables when the files containing those types and const have meaningful names.

**Comment by LeonY1** [comment]
This can be closed now.
