### ISSUE TITLE
Keyboard Usage button doesn't do anything

### ISSUE THREAD

**Issue by LeonY1** [scalabel/scalabel#207]
**Describe the bug**
The Keyboard Usage button doesn't do anything when pressing it in 2D Segmentation. I'm not sure if this has been implement or not.

**To Reproduce**
1. Followed the Guide with the example files
2. Clicked on Submit
3. Used the Task Link
4. Clicked the Keyboard Usage button

**Expected behavior**
It loads up a keyboard usage documentation

**Screenshots**
![Screenshot 2020-07-31 22:09:38](https://user-images.githubusercontent.com/14265005/89092798-8e97b800-d37a-11ea-866d-3127cde067b1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Mozilla Firefox 79.0
 - Version 
 - Node.js 12

**Comment by fyu** [comment]
The keyboard shortcut page is missing now. The quick fix is to add the instructions for all the keyboard shortcuts to the scalabel doc website and make a link to that page directly. A better way is to have a pop-up window to show contextual shortcuts, similar to the gmail shortcut help: https://www.howtogeek.com/wp-content/uploads/2012/05/image189.png.
