### ISSUE TITLE
Not clear where to put images for local use

### ISSUE THREAD

**Issue by alemelis** [scalabel/scalabel#210]
**Describe the bug**
I'm using the docker image and I'd like to annotate images stored in a local folder.

I'm placing the images in `scalabel/local-data/my-images` and my `list.yml` reads

```
- {url: '/my-images/000001.png'}
```

This results in 

```
Failed to load image at /my-images/000001.png
```

where is the error? 
thanks!

**Comment by ChrisP19** [comment]
Scalabel looks in a folder called `items` for local images. You can fix it by putting your images in `scalabel/local-data/items/my-images` and renaming your urls to `/items/my-images/00001.png`.

**Comment by alemelis** [comment]
> Scalabel looks in a folder called `items` for local images. You can fix it by putting your images in `scalabel/local-data/items/my-images` and renaming your urls to `/items/my-images/00001.png`.

It works!
thanks a lot
