### ISSUE TITLE
`image_list.json` but with tracking

### ISSUE THREAD

**Issue by joeyism** [scalabel/scalabel#255]
Hello,

Thank you for your great work. Scalabel is a really awesome tool. I have one question as I'm trying to set up object tracking.

I took the example from [image_list_with_auto_labels_v2.json](https://github.com/scalabel/scalabel/blob/master/examples/image_list_with_auto_labels_v2.json) to create pre-labeled boxes so it is easier for me to label objects. However, I already have a object tracking algorithm. I was wondering if it's possible to use the results of the object tracking and create an `image_list` with object tracking already in place? If so, how can I do that?

Thanks

**Comment by brade31919** [comment]
Hi @joeyism 

To create an `image_lst` from the existing tracking algorithm, you can follow the example from [image_list_with_auto_labels_v2.json](https://github.com/scalabel/scalabel/blob/master/examples/image_list_with_auto_labels_v2.json) with some modifications:

- Images corresponding to the same video should have the same "videoName".
- The same instance across different timesteps (for example, the same car from t0 and t1) needs to have the same "id" in the label corresponding to this instance in "labels" entry.
- Make sure that the "index" entry of each image follows their temporal ordering in the video.
- Similar to the 2D bounding box case, you need to make sure that the "category" and "attributes" in your `image_lst` are consistent with the "Categories" and "Attributes" configurations you used to create the project.
- Remember to add "url" entry to each image in your `image_lst` corresponding to your local path or link to s3 storage. Documentations and examples about local path setting can be found in [installation](https://doc.scalabel.ai/setup.html) or [here](https://github.com/scalabel/scalabel/blob/master/scalabel/tools/README.md) (you can use this example to test your local data loading).

Please let us know if you have any question.

**Comment by joeyism** [comment]
Thank you, I got it to work with tracking from the beginning. In a UI sense, I've encoutered a problem.

I have 2 different objects, and it is clear in the data that they are 2 different objects. However, the displayed bounding box only differentiate them by colours, and one happened to be pink and the other purple, which means that they look very similar and it is very confusing. Is there a way to label each box with a more unique label, or change the display of the boxes somehow?

**Comment by brade31919** [comment]
Hi @joeyism ,

We haven't supported the feature you mentioned yet, but I think the idea of adjusting label colors or choosing colors from a colormap so that the users can better distinguish them is very good. You can propose the idea in our [Discussions](https://github.com/scalabel/scalabel/discussions).
