### ISSUE TITLE
Use the installed webpack instead of npx in the examples

### ISSUE THREAD

**Issue by sashee** [scalabel/scalabel#37]
The build examples in the readme uses npx:

```
node_modules/.bin/npx webpack --config webpack.config.js --mode=production
```

and 

```
node_modules/.bin/npx webpack --watch --config webpack.config.js --mode=development
```

This install a separate webpack, possibly a different version than what the [project uses](https://github.com/scalabel/scalabel/blob/master/package.json#L135). This can lead to errors.

These examples should use the package webpack instead of getting a new one:

```
node_modules/.bin/webpack --config webpack.config.js --mode=production

node_modules/.bin/webpack --watch --config webpack.config.js --mode=development
```

**Comment by fyu** [comment]
Thanks for your suggestions! We are fixing the problems.
