### ISSUE TITLE
Is changing label category of an existing label supported?

### ISSUE THREAD

**Issue by WesleyYue** [scalabel/scalabel#40]
Hi, this might be a dumb question, but is it possible to change the category of a polyline label once it has been drawn? I can't seem to find any way to do this in the UI or the docs.

**Comment by gycn** [comment]
Hi @WesleyYue, you should be able to change the category by clicking on the polyline and selecting the category in the toolbar on the left hand side.

**Comment by WesleyYue** [comment]
Hi @gycn, thanks for the quick reply. I realized my issue was that I was single clicking on the existing polylines instead of double-clicking, which is needed to actually focus on the label.

Dumb mistake on my part. Thanks again!
