### ISSUE TITLE
docker scalabel/www:latest as well as scalabel/www:0.3.0 seem to be broken

### ISSUE THREAD

**Issue by MartinStellmacher** [scalabel/scalabel#447]
After pulling the docker container and starting it as described in README.md / Quick Start any newly created project contains 0 items and exactly 13 categories.

**To Reproduce**

- pull the latest docker: docker pull scalabel/www:latest
- mkdir ./local-data
- start the docker with 
```
docker run -it -v "`pwd`/local-data:/opt/scalabel/local-data" -p \
    8686:8686 -p 6379:6379 scalabel/www \
    node app/dist/main.js \
    --config /opt/scalabel/local-data/scalabel/config.yml \
    --max-old-space-size=8192
```
- go to http://localhost:8686/
- create a new project with
  - Image
  - Bounding Box
  - examples/image_list.yml
  - examples/categories.yml reduced to the first two lines
  - task size 10
- go to the dashboard
- and you will see 13 categories, 0 items

**Expected behavior**
- 2 categories
- a list with all the items contained in image_list.yml

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 running docker 20.10.12
 - Browser Firefox 100.0 and Chrome 101.0.4951.64
 - Version scalabel/www:0.3.0

**Comment by fnobis** [comment]
I experience the same issue. I am using a local dataset, so I thought it would be a configuration issue on my side with the local config (Scalabel worked for me some time ago). However, for me also the example projects remain empty in the browser. I can access the examples files on  s3 manually outside of scalabel but with scalabel, I cant start a label task.

**Comment by fyu** [comment]
Thanks for reporting the issue. We are checking it.
