### ISSUE TITLE
README missing details

### ISSUE THREAD

**Issue by alvinwan** [scalabel/scalabel#47]
- The first instruction is wrong. The git clone command points to an outdated bddrive repo. Instead, should be`git clone git@github.com:scalabel/scalabel.git`
- If you installed node on your machine using homebrew, before osx catalina, you'll need to relink brew's copy of node: https://gist.github.com/berkedel/d1fc6d13651c16002f64653096d1fded
- In 2.ii, there's a sneaky line that says to install redis https://redis.io/topics/quickstart but does not provide commands. The commands on the linked quickstart page involve installing from source; homebrew is cleaner `brew install redis`.
- The repo is missing python dep versions. If you get `AttributeError: module 'yaml' has no attribute 'FullLoader'`, this means you have the wrong pyyaml version. Just update it, `pip install pyyaml --update` or `conda install pyyaml --upgrade`. To the authors: I suggest dumping a pip or conda env and adding it to the README.

**Comment by gycn** [comment]
Hi Alvin, thank you for taking the time to work through the installation procedure and for letting us know about these issues. We have been pushing a lot of changes to the repo recently and the README has gotten outdated as a result. We'll make sure to update it with the information you provided
