### ISSUE TITLE
docker instructions from readme not getting me to project creation 

### ISSUE THREAD

**Issue by orm011** [scalabel/scalabel#51]
Thanks for the tool, I was checking it out to do a small annotation project. 

**Describe the bug**
I followed the Docker instructions from the README step by step (in this repository, not the Berkeley one), but the resulting server is not able to serve / or /create. Instead, the server prints
{"level":"info","message":"Requesting /"}. 

and the page I get is:
"Cannot GET /"

**To Reproduce**
The docker build version I used is the latest one in dockerhub, pointing to
https://www.github.com/scalabel/scalabel/tree/cb78a6d1bf8c7c8517c59cf017192b1618d54f4a,

My docker command is

  docker run -it -v "`pwd`/data:/opt/scalabel/data" -p 8686:8686 -p 6379:6379 scalabel/www     python3.8 scripts/launch_server.py --config /opt/scalabel/data/config.yml

The config is the default_config in commit cb78a6d1bf8c7c8517c59cf017192b1618d54f4a

The URLs I tested are  http://localhost:8686/create
and http://localhost:8686/

**Expected behavior**
I expected to get  the project creation screen like I used to (last time I used this, a few months ago)

**Comment by myhooo** [comment]
Hello, I meet the same question with you. Is there some solutions you have?

**Comment by nicolocarissimi** [comment]
I have the same problem

**Comment by nicolocarissimi** [comment]
Building the image with `docker build . -t scalabel/www` seems to solve this issue, but then #56 happens
