### ISSUE TITLE
Understanding the conversion to coco

### ISSUE THREAD

**Issue by mahamatnoumai** [scalabel/scalabel#522]
I've tried to successfully convert to coco format from scalabel data. 

I did the following:

Python -m scalabel.label.to_coco input det_json.json --output out/results.json --mode det

At the end I got a json result files. Hence my questions what the use case of the --config 

And how to use it? Is it a config file from coco dataset format where it would output similarly like the given one?

**Comment by mahamatnoumai** [comment]
Yeah I tried with the coco config file with added images size, and other infos as well. it worked well. thanks 

In addition to that, I have test the conversion for the ins_seg and the i want to extract the segmentation annotation, but i get only bbox. i just -m to use polygon, it doesn't work 

```
 python3 -m scalabel.label.to_coco --input det_insseg_2d.json --output output_ins_segmentation/ --mode ins_seg -mm polygon 

```

it doesn't work this way. my quesion is how to get the segmentation annotation directly from conversion to coco instead of getting box for after converting.

**Comment by thomasehuang** [comment]
Your usage seems fine to me. Can you show me your annotation file `det_insseg_2d.json`?

**Comment by mahamatnoumai** [comment]
@thomasehuang here is a screenshot of the dataset that I am trying to convert, and if you want to test it out here is the link to the annotations [annotation](https://dl.cv.ethz.ch/shift/discrete/images/train/front/det_insseg_2d.json)

![image](https://github.com/scalabel/scalabel/assets/17758399/14463b0f-020f-4c35-9cd6-1a63eff82728)
![image](https://github.com/scalabel/scalabel/assets/17758399/0d9aa723-0a32-4778-9a2a-44636c6aa043)

**Comment by thomasehuang** [comment]
I understand the concern now. We use RLE format instead of polygon for the conversion to COCO format for segmentation masks, thus the resulting COCO format will be in RLE, which is one of the standard formats and should be able to be used in any data loader. However, if you really need it to be in polygons, we can make an update to the code to support that.

**Comment by mahamatnoumai** [comment]
@thomasehuang I think it is fine, unless u just added as an additional features, it might useful to someone who will need it. 

thank you for your reply
