### ISSUE TITLE
Multiprocessing Error - BDD100k

### ISSUE THREAD

**Issue by pranav-ap** [scalabel/scalabel#524]
I ran the command `python -m scalabel.label.to_coco -m det -i <path> -o <path>`, and got the following error related to multithreading. How can we fix this?

1. Install scalabel using pip
2. Run above command
3. See error

I am trying to convert the BDD100k dataset. I even tried with their tool, but I got the same error. Since they use scalabel, the error must be from the repo.

![image](https://github.com/scalabel/scalabel/assets/11399494/998e3afa-7266-48e2-89f8-9151d3175a81)

![image](https://github.com/scalabel/scalabel/assets/11399494/0d15f73c-4164-4f06-8e12-172c377a5e43)

 - OS: Windows 11

**Comment by thomasehuang** [comment]
This looks like an issue with a new version of pydantic that came out recently. Can you try `pip install -U pydantic==1.9.1` to downgrade it?

**Comment by pranav-ap** [comment]
Thanks it works!
