### ISSUE TITLE
Dashboard is blank

### ISSUE THREAD

**Issue by kyoasu** [scalabel/scalabel#56]
HI. I Compiled the code by docker.When I click the key of "GOTODASHBOARD", it just displays a blank screen. And the terminal show wrong information
{"level":"info","message":"Requesting /create"}
{"level":"info","message":"Requesting /js/create.js"}
{"level":"info","message":"Requesting /postProjectNames"}
{"level":"error","message":"s.isDirectory is not a function"}
{"level":"info","message":"Requesting /postProject"}
{"level":"info","message":"Requesting /dashboard?project_name=example_test4"}
{"level":"info","message":"Requesting /js/dashboard.js"}
{"level":"info","message":"Requesting /postDashboardContents"}
{"level":"error","message":"Path must be a string. Received undefined"}

![1582105228(1)](https://user-images.githubusercontent.com/39193066/74821982-66be1600-533f-11ea-8ded-b3845ddb80f5.png)

And  the page of create project cannot show project name after I created some projects.
![1582105269(1)](https://user-images.githubusercontent.com/39193066/74822078-87866b80-533f-11ea-9a08-91fa6e1c504a.png)

This is URL of dashboard "localhost:8686/dashboard?project_name=example_test4"

Can u teach me how to resolve these problem?Thank u!

**Comment by alex-angelov** [comment]
Any luck with the resolution? I tried compiling from source, downloading the docker image and compiling the docker image, neither of which worked. I also tried it on a clean image of Ubuntu 18.04 (VirtualBox), same problem. Could any of the devs at least give us a stable commit hash, which we could use?

**Comment by nicolocarissimi** [comment]
I compiled it from source using the provided instructions and it worked, though there are still some issues.
The only additional thing I had to do was to force the installation of the latest versions of npm and redis-server.

**Comment by alex-angelov** [comment]
Thank you for your answer. Can you tell me which versions of redis-server and npm you have? Did you change anything in /etc/redis/redis.conf? Are you using Chrome/Firefox?

redis-server --version:
Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3
npm --version:
3.5.2

**Comment by fyu** [comment]
This issue should be fixed by #59. Please pull the latest master and give it a try.

**Comment by kyoasu** [comment]
> This issue should be fixed by #59. Please pull the latest master and give it a try.

I pull the latest iamge on docker, but the page of creat project is empty.
![image](https://user-images.githubusercontent.com/39193066/74896009-15a93300-53ce-11ea-987b-bc635fd541d0.png)

**Comment by fyu** [comment]
@kyoasu Please try again. The docker registry was a little behind the latest master.

**Comment by kyoasu** [comment]
> @kyoasu Please try again. The docker registry was a little behind the latest master.

Wow, it can work! Thank u!
But I found another issues, the task cannot submit when I click the key of 'submit'. the webpage is keep showing 'saving in progress'. 
![image](https://user-images.githubusercontent.com/39193066/74907063-962b5c00-53ed-11ea-8c0b-72cf80c5527b.png)

And I tried to back to dashboard, nothing in submitted list.
![image](https://user-images.githubusercontent.com/39193066/74907125-b3f8c100-53ed-11ea-848c-41aad57204bd.png)

**Comment by fyu** [comment]
We will investigate this issue. For now, you can just click the save icon (second from right) to save your results. The submission button is supposed to leave an additional marker on the dashboard, which doesn't affect the annotations.

**Comment by kyoasu** [comment]
Thank you very much! u are so nice!

**Comment by nicolocarissimi** [comment]
> Thank you for your answer. Can you tell me which versions of redis-server and npm you have? Did you change anything in /etc/redis/redis.conf? Are you using Chrome/Firefox?
> 
> redis-server --version:
> Redis server v=4.0.9 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=9435c3c2879311f3
> npm --version:
> 3.5.2

redis 5.0.7
npm 6.13.4
