### ISSUE TITLE
Using my own data does not work

### ISSUE THREAD

**Issue by alex-angelov** [scalabel/scalabel#64]
Running through docker. Trying to use my own data returns errors when opening the tasks, e.g:
"Failed to load image at /localhost:8686/images/one.jpg"

I have placed the two images in scalabel/app/src/images. Contents of image_list.yml:
- {url: 'localhost:8686/images/one.jpg'}
- {url: 'localhost:8686/images/two.jpg'}

I thought it might be a formatting issue. Creating image_list.yml via prepare_data.py script has the same issue. 

Maybe the image_list.yml file has to be formatted differently, or the images have to be placed in another directory?

**Comment by gycn** [comment]
Hi @alex-angelov, you must place your images in the `app/dist` folder

**Comment by alex-angelov** [comment]
Hi @gycn, I created folder dist, because it did not exist before and placed the data there. However, I am still getting the same error.

**Comment by ramfalas** [comment]
I have the same problem.

**Comment by alex-angelov** [comment]
**Still not working**. Below is an approach I tried.
1) Run the docker image with the readme line.
List the containers:
2) docker ps -a
Copy the data to the running container:
3) docker cp dist/images <docker_container_hash>:/opt/scalabel/app/dist/
Verify the data is there. Open a new terminal. This will give you a shell in the image so you can explore it:
4) docker exec -it <docker_container_hash> bash
Try to create a project. I get the same error as before.

**Comment by gycn** [comment]
Hi @alex-angelov, I will look into this issue with docker more. In the meantime, could you try compiling the code locally and running the server without docker? Please make sure to use node version >= 12.11 and npm version >= 6.11

**Comment by fyu** [comment]
@alex-angelov You don't have to `cp` the images into docker. The docker command below works for me. Can you give it a try?

```
docker run -it -v "`pwd`/data:/opt/scalabel/data" -v "`pwd`/app/dist/images:/opt/scalabel/app/dist/images" -p 8686:8686 -p 6379:6379 scalabel/www \
    python3.8 scripts/launch_server.py --config /opt/scalabel/data/config.yml
```

**Comment by alex-angelov** [comment]
@fyu I tried it and it did not work. Also tried again in a (fresh) Ubuntu VM, without any success.

**Comment by ramfalas** [comment]
@alex-angelov for me it works when the content of image_list.yml is:
- url: /images/one.jpg
- url: /images/two.jpg
....
So, url without 'localhost:8686'.

**Comment by alex-angelov** [comment]
That works, cheers : )
